### PR TITLE
Guide/How Companies Fix Vulnerabilities

### LINKED ISSUE #5473: Gated page: Fix & find vulnerabilities e-book
Stakeholders: Nick, Fabiana
What? E-book to be promoted on paid campaign 
Why? Capture leads with engaging content 
The existing template for [guides]( https://about.sourcegraph.com/guides/continuous-developer-onboarding) can be reused for this.

🔗[Landing page copy](https://docs.google.com/document/d/1lOr2FynLaL2U3flzAuQzm3LNNzGpCANdWPtRFG2ozIA/edit)
[🔗Meta](https://docs.google.com/spreadsheets/d/1W_jBN-pSWJ0bURk9z7rtb4swvf-9H5urLe9Zj4k_XwQ/edit#gid=715450113) ✅
[How companies fix vulnerabilities Ebook.pdf](https://github.com/sourcegraph/about/files/8952123/How.companies.fix.vulnerabilities.Ebook.pdf)

Embed form: 
Add "Download the e-book"
Embed form: 
<script charset="utf-8" type="text/javascript" src="[//js.hsforms.net/forms/v2.js](https://sourcegraph.slack.com//js.hsforms.net/forms/v2.js)"></script>
<script>
  hbspt.forms.create({
    region: "na1",
    portalId: "2762526",
    formId: "610debf1-bbce-45d6-a492-6858b5b3db18"
  });
</script>

**Test form submission:**
1. Check HubSpot syntax #5409 
2. Check that form thank you message shows correct link to PDF
3. Check the email that is generated and that the links are correct

Asana: https://app.asana.com/0/1200095757619647/1202429370797707/f

### PR DESCRIPTION
**Pull request by zlonko**
This closes #5473. It adds the gated page for the "How Companies Fix Vulnerabilities" e-book.

### Changelog
- Adds `guides/how-google-fixes-vulnerabilities.tsx`
- Adds `sg-how-companies-fix-vulnerabilities.pdf` for download

### Notes
- This guide page will be updated with the new Hubspot form syntax in #5483

### Test

1. Ensure prettier has standardized the proposed changes.
2. Navigate to `/guides/how-google-fixes-vulnerabilities.tsx`
3. Please check that the copy aligns with the doc
4. Please check that the guide downloads properly on form submission

### CODE REVIEW

File: src/pages/guides/how-google-fixes-vulnerabilities.tsx [hunk 1]
```diff
@@ -0,0 +1,48 @@
+import { FunctionComponent } from 'react'
+
+import { Layout, GatedResourceLayout } from '@components'
+
+export const Guide: FunctionComponent = () => (
+    <Layout
+        meta={{
+            title: 'How Google and Others and Fix Vulnerabilities | Sourcegraph',
```
Comment (bretthayes) [inline src/pages/guides/how-google-fixes-vulnerabilities.tsx:8]: I'm thinking this should be "*find* and fix" and also be read without capitalization on "Others", "Find", "Fix", and "Vulnerabilities".

```suggestion
            title: 'How Google and others find and fix vulnerabilities | Sourcegraph',
```

@fabicastp can you shed some light on the capitalization here being more of a sentence-like title?

File: src/pages/guides/how-google-fixes-vulnerabilities.tsx [hunk 2]
```diff
@@ -0,0 +1,48 @@
...
+                'See how tech companies large and small address code security. In this post, we explore how Google, Microsoft, Lyft, GitLab, and Atlassian find and fix vulnerabilities.',
+        }}
+        className="navbar-white"
+    >
+        <GatedResourceLayout
+            title="How Google, Microsoft, Lyft, GitLab, and Atlassian find and fix vulnerabilities"
+            formLabel="Download the e-book"
+            form={{
+                formId: '610debf1-bbce-45d6-a492-6858b5b3db18',
+                onFormSubmitted: () => window.open('/guides/sg-how-companies-fix-vulnerabilities.pdf'),
```
Comment (bretthayes) [inline src/pages/guides/how-google-fixes-vulnerabilities.tsx:19]: As an improvement, we could name the PDF with the title of the PDF instead of it showing the filename in the tab. Check out [this comment for reference](https://github.com/sourcegraph/about/pull/5498#pullrequestreview-1015357937). 🤓

File: src/pages/guides/how-google-fixes-vulnerabilities.tsx (hunk 1 above)
Comment (zlonko) [reply src/pages/guides/how-google-fixes-vulnerabilities.tsx]: @bretthayes You eagle eye, you! Thank you for catching this error. I accepted the commit suggestion because it corrects the grammar. Pending @fabicastp we can alter the casing of the phrase, too.

Comment (zlonko) [reply src/pages/guides/how-google-fixes-vulnerabilities.tsx]: In a chat with Fabiana, it was decided that we go with sentence case in our titles when possible.

Comment (bretthayes) [reply src/pages/guides/how-google-fixes-vulnerabilities.tsx]: Awesome! Sounds great! @zlonko Thanks @fabicastp! 🟢

**Review by st0nebraker — APPROVED** [review]

File: src/pages/guides/how-google-fixes-vulnerabilities.tsx (hunk 2 above)
Comment (zlonko) [reply src/pages/guides/how-google-fixes-vulnerabilities.tsx:19]: What a helpful tool. Thanks for the rec, Brett! I've updated the PDF here, which displays the title now in browser. I will update the file in the paired ticket as well.

Screen Shot 2022-06-23 at 11 05 27 AM

Comment (bretthayes) [reply src/pages/guides/how-google-fixes-vulnerabilities.tsx:19]: Awesome!! Thanks @zlonko!

**Review by bretthayes — APPROVED** [review]

**Comment by zlonko** [comment]
@elzannewentzel This is ready for Fabiana and Nick to take a look!
