### PR TITLE
Bugfix/Blog post link to author url

### LINKED ISSUE #5323: Blog author text is not rendering as links
Nick Moore reported that Blog author text is not currently rendering as links. The frontmatter allows for "author" and "authorUrl" but in at least the two posts linked, and probably more, the author titles don't end up being clickable. Is this a bug or are we inputting "authorUrl" incorrectly?

Relevant links: Asana card(s), Github issues, reference links, RFCs, docs, etc.
https://github.com/sourcegraph/about/pull/5303
https://github.com/sourcegraph/about/blob/main/blogposts/2022/introducting-migrator-service.md + https://about.sourcegraph.com/blog/introducing-migrator-service/

### PR DESCRIPTION
**Pull request by st0nebraker**
Closes #5323 by making use of `authorUrl` prop to link out to author url when present

### Test
- Nav to https://about.sourcegraph.com/blog/introducing-migrator-service/ or any blog post to ensure `author` under title is a working link

### CODE REVIEW

File: website/src/components/blog/BlogPost.tsx [hunk 1]
```diff
@@ -46,9 +46,17 @@ export const BlogPost: React.FunctionComponent<Props> = ({
...
                 </h1>
-                <p className="blog-post__byline mb-0">
-                    {post.frontmatter.author} on {post.frontmatter.publishDate}
-                </p>
+                {post.frontmatter.author && post.frontmatter.publishDate && (
+                    <p className="blog-post__byline mb-0">
+                        {post.frontmatter.authorUrl ?
+                            <a href={post.frontmatter.authorUrl} target="_blank" rel="nofollow noreferrer">
+                                {post.frontmatter.author}
+                            </a> :
```
Comment (zlonko) [inline website/src/components/blog/BlogPost.tsx]: In the future, this may require an internal `<Link>` if employee profiles end up within the scope of About. However, we don't have a case for this at this time, because all of the links are outgoing.

**Review by bretthayes — CHANGES_REQUESTED** [review]
Looks good to me! Just one minor improvement 🤓

File: website/src/components/blog/BlogPost.tsx [hunk 2]
```diff
@@ -46,9 +46,17 @@ export const BlogPost: React.FunctionComponent<Props> = ({
...
+                            <span>{post.frontmatter.author}</span>
```
Comment (zlonko) [inline website/src/components/blog/BlogPost.tsx:56]: There are a few cases where blog posts have more than one author. Now that the link is introduced, those blogposts group both authors into one hyperlink, sometimes to a site representing just one of the two authors. I don't think it's within the scope of this ticket, but it may be useful to support multiple author/authorUrl pairings in the future.

/blog/real-weakest-link-in-software-supply-chain-security/
Screen Shot 2022-05-04 at 9 17 52 AM

/blog/remote-software-development-made-easier/
Screen Shot 2022-05-04 at 9 19 20 AM

**Review by zlonko — DISMISSED** [review]
This looks good to me, and the links that I tested work as expected! I noticed a couple of opportunities for the links to behave differently, but neither of them block this ticket.

File: website/src/components/blog/BlogPost.tsx (hunk 1 above)
Comment (st0nebraker) [reply website/src/components/blog/BlogPost.tsx]: Yes, maybe evaluating when there's an outside link with `http` in the url and using a `Link` or `a` tag accordingly

File: website/src/components/blog/BlogPost.tsx (hunk 2 above)
Comment (zlonko) [reply website/src/components/blog/BlogPost.tsx:60]: That sounds good!

File: website/src/components/blog/BlogPost.tsx [hunk 3]
```diff
@@ -46,9 +46,22 @@ export const BlogPost: React.FunctionComponent<Props> = ({
                         post.frontmatter.title
                     )}
                 </h1>
-                <p className="blog-post__byline mb-0">
-                    {post.frontmatter.author} on {post.frontmatter.publishDate}
-                </p>
+                {post.frontmatter.author && post.frontmatter.publishDate && (
+                    <p className="blog-post__byline mb-0">
+                        {post.frontmatter.authorUrl ? (
+                            post.frontmatter.authorUrl.includes('http') ? (
```
Comment (zlonko) [inline website/src/components/blog/BlogPost.tsx:52]: Nice!! This looks great!

**Review by zlonko — APPROVED** [review]
Thank you for including the `<Link>` modification!

**Review by bretthayes — APPROVED** [review]
