### PR TITLE
Script loading strategies, HubSpot hook refactor, and Triblio script fix

### LINKED ISSUE #5373: Missing script on use cases page for Triblio
The Triblio team reported that the [Use Cases LP](https://about.sourcegraph.com/use-cases) does not have the tracking script for Tracking Activity over Live Campaign Ad Group.

**Instructions**

Webpage Personalization Script
Place this code in your <head> tag before any other scripts.
<script type='text/javascript' data-cfasync='false' src='https://tribl.io/h.js?orgId=Yee6bMKj7QSARqAePdE8'></script>

Analytics and Overlay Cards
Copy this embed code and paste it inside the <body> tag in all pages where you want to deploy 
campaigns.
<script type='text/javascript' data-cfasync='false' src='https://tribl.io/footer.js?orgId=Yee6bMKj7QSARqAePdE8'></script>

### PR DESCRIPTION
**Pull request by bretthayes**
This changes our script loading strategies for our 3rd party integrations and closes #5373.

### Changelog
- Changed [script loading strategies](https://nextjs.org/docs/basic-features/script#strategy) for 3rd party integrations in `_app.tsx`
  - `beforeInteractive` ensures critical scripts are loaded before render (in the head)
  - `afterInteractive` loads non critical scripts after render (in the body)
- Moved our Clearbit script integration to our HubSpot hook since Clearbit is a HubSpot form enhancement. This ensures we aren't loading scripts unnecessarily on pages that don't need it. Note that [jQuery is required](https://help.clearbit.com/hc/en-us/articles/360037598334-Set-Up-Clearbit-Enrichment-for-HubSpot-Forms#:~:text=To%20confirm%20jQuery%20is%20installed%20on%20your%20site) for our Clearbit integration unfortunately. Also note that Clearbit returns a 401 on local.
- Refactored our HubSpot hook to allow for multiple script integrations. We now have get/remove/load script element functions.
- Added Triblio Analytics and Overlay Cards script

### Test

1. Ensure linting passes.
2. Ensure prettier has standardized the proposed changes.
3. Ensure dev and production builds work.
4. Ensure `jQuery` and `Clearbit` scripts only load in the head on pages with HubSpot forms. You can search for the script tag ids.
5. Ensure our Triblio (personalization), Google Analytics, and Google Tag Manager scripts load in the head
6. Ensure our Triblio (analytics and overlay cards), Cookiebot and Drift scripts load in the body

### CODE REVIEW

File: src/pages/_app.tsx [hunk 1]
```diff
@@ -17,15 +17,26 @@ const App = ({ Component, pageProps }: AppProps): ReactNode => {
 
             {/* // Import all top-level scripts here: https://nextjs.org/docs/messages/no-script-in-document-page */}
 
-            {/* Triblio "Webpage Personalization" for Sales/Marketing */}
+            {/* Triblio "Webpage Personalization" */}
             <Script
-                data-cfasync="false"
                 type="text/javascript"
                 src="https://tribl.io/h.js?orgId=Yee6bMKj7QSARqAePdE8"
```
Comment (zlonko) [inline src/pages/_app.tsx:23]: This appears to be loading in the body by `afterInteractive`, when we anticipate it to load in the head by `beforeInteractive`. Is this expected?

Screen Shot 2022-05-25 at 12 56 26 PM

File: src/pages/_app.tsx [hunk 2]
```diff
@@ -17,15 +17,26 @@ const App = ({ Component, pageProps }: AppProps): ReactNode => {
...
+                strategy="beforeInteractive"
+            />
+            
+            {/* Triblio "Analytics and Overlay Cards" */}
+            <Script
+                type="text/javascript"
+                src="https://tribl.io/footer.js?orgId=Yee6bMKj7QSARqAePdE8"
```
Comment (zlonko) [inline src/pages/_app.tsx:30]: The Triblio footer script (analytics and overlays) doesn't appear to load on pages: 

Screen Shot 2022-05-25 at 1 07 38 PM

**Review by zlonko — COMMENTED** [review]
Thank you for walking through this with me. I am cloudy on the Triblio scripts: Personalization seems to load in the wrong place, while I could not locate Analytics and Overlay Cards. (See below.)

I am just getting up to speed on these and may not be aware of a better debugging method. I am eager to learn, so please let me know if I made a mistake!

File: src/pages/_app.tsx (hunk 1 above)
Comment (bretthayes) [reply src/pages/_app.tsx:24]: Hmm, I'm not seeing the same but I did happen to add some ids to the scripts for extra measure even though [Next only requires ids for inline scripts](https://nextjs.org/docs/basic-features/script#:~:text=The%20id%20property%20is%20required%20for%20inline%20scripts%20in%20order%20for%20Next.js%20to%20track%20and%20optimize%20the%20script.). I'm wondering if that maybe fixed it?

---

### Website personalization script (loading in the head)
Screen Shot 2022-05-25 at 3 05 31 PM

---

### Analytics and overlay cards (loading in the body)
Screen Shot 2022-05-25 at 3 06 40 PM

File: src/pages/_app.tsx (hunk 2 above)
Comment (bretthayes) [reply src/pages/_app.tsx:32]: Hmm, I'm not able to replicate. I see the scripts loaded in Sources and Network. I also see the `TriblioAnalyticsObject` in the console.

Screen Shot 2022-05-25 at 3 14 49 PM
Screen Shot 2022-05-25 at 3 15 04 PM
Screen Shot 2022-05-25 at 3 15 25 PM
Screen Shot 2022-05-25 at 3 15 40 PM
Screen Shot 2022-05-25 at 3 16 43 PM

File: src/pages/_app.tsx (hunk 1 above)
Comment (zlonko) [reply src/pages/_app.tsx:24]: Awesome! I just checked and now they both load in the correct places. Adding the IDs seemed to do the trick.

File: src/pages/_app.tsx (hunk 2 above)
Comment (zlonko) [reply src/pages/_app.tsx:32]: As noted in my other comment, this now loads in the body as expected now that you added the IDs!

**Review by zlonko — APPROVED** [review]
The Triblio scripts load as expected now. Thank you for checking out my questions! 👍

File: src/hooks/hubSpot.ts [hunk 3]
```diff
@@ -51,24 +52,45 @@ interface HookProps {
...
+        } else {
+            newScriptElement.src = script
+        }
+        document.head.append(newScriptElement)
+        return newScriptElement
     }
 
-    return script
+    return scriptElement
 }
```
Comment (st0nebraker) [inline src/hooks/hubSpot.ts:94]: ✨  This is great!

File: src/pages/_app.tsx [hunk 4]
```diff
@@ -58,13 +75,15 @@ const App = ({ Component, pageProps }: AppProps): ReactNode => {
...
-            {/* Add jQuery as a dependency for Clearbit - without this Clearbit doesn't work */}
-            <Script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js" />
-
             {/* Drift */}
-            <Script type="text/javascript" id="drift">
+            <Script
+                id="drift"
+                type="text/javascript"
+                strategy="afterInteractive"
+            >
```
Comment (st0nebraker) [inline src/pages/_app.tsx:86]: Out of curiosity, what is drift doing for us?
