### PR TITLE
Bug fixes and improvements

### LINKED ISSUE #5637: Fix anchor links hiding content under top nav
What? Anchor links linking to content sections hide content under our fixed top nav.

Fix: Enhance the navigation experience so there's enough spacing between the bottom of the top nav and the top of linked content sections.

Why? To prevent headers or content within content sections from being hidden under our top nav.

### LINKED ISSUE #5709: Restore release post Go script
This script was removed as part of our replatform initiative and needs to be restored for release posts:
- [bin/generate_changelog_items.go](https://github.com/sourcegraph/about/commit/611f024b9e1bb340c043b170d64b8f963996311e#diff-d674dff9359444d26ec653bc9a55368ae7f8008a6c0db791d8517e3befbb6e06)

### PR DESCRIPTION
**Pull request by bretthayes**
### Changelog
- Restores `generateChangelogItems.go` for generating changelog items for release posts. This closes #5709. Also updated the handbook to reflect this in sourcegraph/handbook#4787
- Fixes a discrepancy with our Background component where multiple utility classes would be applied based on multiple conditions being true. This caused a utility class conflict noticed on the old `CaseStudyLayout` for the `CtaSection`. Now they are scoped to their respective conditions in preparation for moving towards more code-based gradients and utility classes for backgrounds. This will help with refactoring when we remove our bg images.
- Removed another duplicate cta section (`RequestDemoForm`) in lieu of our new `CtaSection`
- Added a `scrollToAnchor` hook which closes #5637
- Updated `caniuse-lite` from a lint warning suggestion

### Test

1. Ensure prettier has standardized the proposed changes.
2. Ensure anchor links smooth scroll to the top of their element (example: `/terms/security#managed-sourcegraph-instances`)
3. Ensure CtaSection on old case study layouts have white text on a black background (example: `/case-studies/cloudflare-accelerates-debugging-and-improves-security`)

### CODE REVIEW

File: src/hooks/scrollToAnchor.ts [hunk 1]
```diff
@@ -0,0 +1,31 @@
...
+                window.scrollTo({
+                    top: scrollToPosition,
+                    behavior: 'smooth',
+                })
+            }
+        }, 100)
+
+        return () => clearTimeout(scrollToElement)
+    }, [])
+}
```
Comment (st0nebraker) [inline src/hooks/scrollToAnchor.ts:31]: 👏🏻 

I'm curious why this is implemented as a custom hook as opposed to a function running on mount in `_app`, could you explain?

**Review by st0nebraker — APPROVED** [review]
LGTM!

File: src/hooks/scrollToAnchor.ts (hunk 1 above)
Comment (bretthayes) [reply src/hooks/scrollToAnchor.ts:31]: I didn't want to bloat the app.tsx file, and since we can't necessarily use a collocated structure yet, it felt like a good place to put it for now until Next.js releases their layouts update.
